#!/bin/bash
# insert the following in output html files generated by sphinx, which are in _build/html/:
# 1. a justfont javascript after the </head> tag
# 2. a disqus javascript before the <div role="contentinfo"> tag
# 3. a github ribbon image, replacing "View page source" (at the upper-right corner)
# 4. a favicon before the </head> tag (only in index.html)
# by Whyjay Zheng, first edition on 2016/1/12, last edited on 2017/10/22 (added google fonts for english)

html_files=$(ls _build/html/*.html _build/html/en/*.html)

google_fonts=$(cat _static/google_fonts.txt)
jf_string=$(cat _static/jf_code.txt)
disqus_string=$(cat _static/disqus_code.txt)
github_ribbon=$(cat _static/github_ribbon.txt)
favicon_string=$(cat _static/favicon.txt)
localemenu=$(cat _static/localemenu.txt)

# refer to the escape characters...
# http://unix.stackexchange.com/questions/32907/what-characters-do-i-need-to-escape-when-using-sed-in-a-sh-script
google_fonts=${google_fonts//\\/\\\\}     # changes all "\" to "\\"
google_fonts=${google_fonts//\[/\\\[}     # changes all "[" to "\["
google_fonts=${google_fonts//\]/\\\]}     # changes all "]" to "\]"
google_fonts=${google_fonts//\$/\\\$}     # changes all "$" to "\$"
google_fonts=${google_fonts//\./\\\.}     # changes all "." to "\."
google_fonts=${google_fonts//\*/\\\*}     # changes all "*" to "\*"
google_fonts=${google_fonts//\^/\\\^}     # changes all "^" to "\^"
google_fonts=${google_fonts//\//\\\/}     # changes all "/" to "\/"
google_fonts=${google_fonts//\"/\\\"}     # changes all '"' to '\"'

jf_string=${jf_string//\\/\\\\}     # changes all "\" to "\\"
jf_string=${jf_string//\[/\\\[}     # changes all "[" to "\["
jf_string=${jf_string//\]/\\\]}     # changes all "]" to "\]"
jf_string=${jf_string//\$/\\\$}     # changes all "$" to "\$"
jf_string=${jf_string//\./\\\.}     # changes all "." to "\."
jf_string=${jf_string//\*/\\\*}     # changes all "*" to "\*"
jf_string=${jf_string//\^/\\\^}     # changes all "^" to "\^"
jf_string=${jf_string//\//\\\/}     # changes all "/" to "\/"
jf_string=${jf_string//\"/\\\"}     # changes all '"' to '\"'

disqus_string=${disqus_string//\\/\\\\}     # changes all "\" to "\\"
disqus_string=${disqus_string//\[/\\\[}     # changes all "[" to "\["
disqus_string=${disqus_string//\]/\\\]}     # changes all "]" to "\]"
disqus_string=${disqus_string//\$/\\\$}     # changes all "$" to "\$"
disqus_string=${disqus_string//\./\\\.}     # changes all "." to "\."
disqus_string=${disqus_string//\*/\\\*}     # changes all "*" to "\*"
disqus_string=${disqus_string//\^/\\\^}     # changes all "^" to "\^"
disqus_string=${disqus_string//\//\\\/}     # changes all "/" to "\/"
disqus_string=${disqus_string//\"/\\\"}     # changes all '"' to '\"'

github_ribbon=${github_ribbon//\\/\\\\}     # changes all "\" to "\\"
github_ribbon=${github_ribbon//\[/\\\[}     # changes all "[" to "\["
github_ribbon=${github_ribbon//\]/\\\]}     # changes all "]" to "\]"
github_ribbon=${github_ribbon//\$/\\\$}     # changes all "$" to "\$"
github_ribbon=${github_ribbon//\./\\\.}     # changes all "." to "\."
github_ribbon=${github_ribbon//\*/\\\*}     # changes all "*" to "\*"
github_ribbon=${github_ribbon//\^/\\\^}     # changes all "^" to "\^"
github_ribbon=${github_ribbon//\//\\\/}     # changes all "/" to "\/"
github_ribbon=${github_ribbon//\"/\\\"}     # changes all '"' to '\"'

favicon_string=${favicon_string//\\/\\\\}     # changes all "\" to "\\"
favicon_string=${favicon_string//\[/\\\[}     # changes all "[" to "\["
favicon_string=${favicon_string//\]/\\\]}     # changes all "]" to "\]"
favicon_string=${favicon_string//\$/\\\$}     # changes all "$" to "\$"
favicon_string=${favicon_string//\./\\\.}     # changes all "." to "\."
favicon_string=${favicon_string//\*/\\\*}     # changes all "*" to "\*"
favicon_string=${favicon_string//\^/\\\^}     # changes all "^" to "\^"
favicon_string=${favicon_string//\//\\\/}     # changes all "/" to "\/"
favicon_string=${favicon_string//\"/\\\"}     # changes all '"' to '\"'

localemenu=${localemenu//\\/\\\\}     # changes all "\" to "\\"
localemenu=${localemenu//\[/\\\[}     # changes all "[" to "\["
localemenu=${localemenu//\]/\\\]}     # changes all "]" to "\]"
localemenu=${localemenu//\$/\\\$}     # changes all "$" to "\$"
localemenu=${localemenu//\./\\\.}     # changes all "." to "\."
localemenu=${localemenu//\*/\\\*}     # changes all "*" to "\*"
localemenu=${localemenu//\^/\\\^}     # changes all "^" to "\^"
localemenu=${localemenu//\//\\\/}     # changes all "/" to "\/"
localemenu=${localemenu//\"/\\\"}     # changes all '"' to '\"'

# start to insert

for html_f in $html_files
do
    # ==== Attaching google fonts code ====
    if grep -q 'googleapis' $html_f; then
        echo skip ${html_f##*/} - already attached the google fonts code
    else
        echo ----- Attaching google fonts code to ${html_f##*/} ...
        # insert a new line after theme.css line
        sed -i "/theme.css/a\ $google_fonts" $html_f
    fi
    # ==== Attaching jf code ====
    if grep -q '^ <script' $html_f; then
        echo skip ${html_f##*/} - already attached the jf code
    else
        echo ----- Attaching jf code to ${html_f##*/} ...
        # insert a new line after </head> tag
        sed -i "/<\/head>/a\ $jf_string" $html_f
    fi
    # ==== Attaching disqus code ====
    if grep -q 'disqus_thread' $html_f; then
        echo skip ${html_f##*/} - already attached the disqus code
    else
        echo ----- Attaching disqus code to ${html_f##*/} ...
        dyn_id=${html_f##*/}
        dyn_id=${dyn_id%%.*}
        unique_disqus_string=${disqus_string//DYNAMIC_ID/$dyn_id}
        sed -i "/<div\ role=\"contentinfo\">/i\ $unique_disqus_string" $html_f
    fi
    # ==== Replacing "View source file" with a github ribbon ====
    if grep -q 'forkme_right_green' $html_f; then
        echo skip ${html_f##*/} - already attached the github ribbon
    else
        if grep -q 'View page source' $html_f; then
            echo ----- Attaching a github ribbon to ${html_f##*/} ...
            sed -i "/View page source/a\ $github_ribbon" $html_f
            sed -i "/View page source/d" $html_f
        else
            echo skip ${html_f##*/} - No "View page source"
        fi
    fi
done

# or     $ find . -type f -exec sed -e 's/cpu/memory/ig' '{}' \;
# see http://blog.miniasp.com/post/2010/12/24/Useful-tool-Find-and-Replace-with-sed-command.aspx

# ==== Add favicon in index.html ====

indpage="_build/html/index.html"

if grep -q 'shortcut icon' $indpage; then
    echo skip favicon - already replaced
else
    echo ----- Replacing favicon to ${indpage##*/} ...
    # insert a new line before </head> tag
    sed -i "/<\/head>/i\ $favicon_string" $indpage
fi

# ==== Add locate menu ====

for html_f in $html_files
do
    if grep -q 'clearfix' $html_f; then
        echo skip locale - already added
    else
        html_name=${html_f##*/}
        echo ----- Adding locale to $html_name ...
        if ( echo $html_f | grep -q '/en/' ); then
            localemenu_each=${localemenu/LinkToChinese/\\.\\.\\\/${html_name/./\\.}}
            localemenu_each=${localemenu_each/LinkToEnglish/${html_name/./\\.}}
        else
            localemenu_each=${localemenu/LinkToChinese/${html_name/./\\.}}
            localemenu_each=${localemenu_each/LinkToEnglish/en\\\/${html_name/./\\.}}
        fi
        # delete 2 lines before class "wy-menu wy-menu-vertical"
        vi -e - $html_f <<COMMANDEND
g/wy-menu wy-menu-vertical/-2,-1d
wq
COMMANDEND
        # add locale menu body
        sed -i "/wy-menu wy-menu-vertical/i\ $localemenu_each" $html_f
        # add a </div> back, which was deleted by vi
        sed -i "/wy-menu wy-menu-vertical/i\ <\/div>" $html_f
    fi
done

# ==== Replace project name in Chinese with English ====

en_html_files=$(ls _build/html/en/*.html)

for html_f in $en_html_files
do
    echo ----- Finalizing English Locale of ${html_f##*/} ...
    sed -i -e 's/GMT 教學手冊/GMT Tutorials /g' $html_f
    sed -i -e 's/zzz_replace_token/English/g' $html_f
done

zhtw_html_files=$(ls _build/html/*.html)

for html_f in $zhtw_html_files
do
    echo ----- Finalizing Zhtw Locale of ${html_f##*/} ...
    sed -i -e 's/zzz_replace_token/中文 (台灣)/g' $html_f
done
